<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BlogArticleComment extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (BlogArticleComment $comment) {
            if (is_null($comment->parent_id)) {
                $comment->level = 0;
                $comment->path = '-';
            } else {
                $comment->level = $comment->parent->level + 1;
                $comment->path = $comment->parent->path . $comment->parent->id . '-';
            }
        });
    }

    public function parent()
    {
        return $this->belongsTo(BlogArticleComment::class, 'parent_id', 'id');
    }
}
